### ISSUE TITLE
Blocking sites like reddit etc

### ISSUE THREAD

**Issue by herpiko** [macmorning/pomodoro-webext#1]
How about feature that block selected sites on work-time?

**Comment by macmorning** [comment]
Blocking would require setting a proxy, or an invasive content-script. I would prefer to keep this extension as simple and non intrusive as possible. Perhaps a "shaming" notification would do ?

Could use chrome.tabs.onUpdated.addListener(function callback) from the background script for this.

**Comment by macmorning** [comment]
Closing this because it would require some broad permissions on open tabs.
