### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by GK-ASCM** [macmorning/pomodoro-webext#11]
I would love to have a ticking clock option

**Comment by macmorning** [comment]
Hello, thank you for your feedback.
Do you mean you'd like to have the sound of a clock ticking? Wouldn't that be annoying when you try to concentrate on your work?

**Comment by GK-ASCM** [comment]
Faint clock ticking subconsciously reminds people about time ticking by. 

When I am working on Pomodoro, I have some music playing and have the clock ticking in the background. So it should be possible to control the volume.

Should be an option of course. Some people may find it annoying.

**Comment by macmorning** [comment]
Hello,
Sorry I don't think I'll do that, this would stretch the "keep it simple" policy and I don't think many people would use the option.
