### ISSUE TITLE
add statistics?

### ISSUE THREAD

**Issue by dyana0908** [macmorning/pomodoro-webext#12]
recently i've been trying different pomodoro clocks extensions and i found that the best one is this one, but if it's possible i'd like if there were stats(es. how many pomodoros i did in total or this week ecc.).  if not it's okay!

**Comment by macmorning** [comment]
Sure, that could be an option.
First it could be in tables, then in graphs later on. 
I'd like to avoid including an external graph lib but there are some light ones out there.
Data could be stored in the local storage, but I'll have to make sure the custom ring sound doesn't take too much space already.

**Comment by macmorning** [comment]
I dont' like current implementation so I'll keep this issue open for now.
Requesting the downloads permission can be made optional, only if the user enables the reporting feature for example.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions

**Comment by macmorning** [comment]
Done for the data gathering and export part.
