### ISSUE TITLE
Please consider making the link to this repo more prominent on the Firefox addins page for this extension

### ISSUE THREAD

**Issue by creuter-rws** [macmorning/pomodoro-webext#14]
I was not able to find a link to this repo from the [Firefox extension page](https://addons.mozilla.org/en-CA/firefox/addon/pomodoro-clock/) for this repository and had to download the XPI and google a phrase in the README.md.

(This was spurred by my wanting to find out why it needed suspicious-looking new permissions and me being insufficiently observant to notice the change notes in the addon page.)

**Comment by macmorning** [comment]
Hey
Glad you found your way then.
The link is on the extension homepage but I will add it to the description itself.
Thank you!

**Comment by macmorning** [comment]
Added the "?" icon on the top right of the extension popup.

**Comment by creuter-rws** [comment]
:+1:
