### ISSUE TITLE
Feedback - Accessibility - What about a visual alarm instead of or in addition to sound ?

### ISSUE THREAD

**Issue by AurelBouchard** [macmorning/pomodoro-webext#18]

**Comment by macmorning** [comment]
Hey @AurelBouchard thanks for your feedback. If you granted the "notifications" permission to the extension, then a toaster-style should popup when the alarm is triggering. Which browser do you use?

**Comment by AurelBouchard** [comment]
Yes, that works fine. Actually that popup in the corner the way that should, but it is far from where I look at. So I don't see it if I don't expect it ... maybe a blinking notification or something very colorful could catch the eye more easily ?
anyway great addon

**Comment by macmorning** [comment]
Ok I'll look into it!
I'll check if I can use an animated image for the notification, or have a popup from the extension icon. It should be disabled by default because it could be annoying on small resolution screens.

**Comment by macmorning** [comment]
Hello,
Sorry after a second thought I prefer to let the browser & the OS handle how the notification is displayed and personalizable.
