### ISSUE TITLE
Over Microsoft Edge on restart it keeps showing last count over icon

### ISSUE THREAD

**Issue by KiranHappy** [macmorning/pomodoro-webext#20]
After Microsoft Edge restart it keeps showing some value over icon, which misleads if it's already running.
Into Firefox it's blank.
Into another ticked i had suggested to start the counter at startup, but stale counter should be removed first.

**Comment by macmorning** [comment]
Hello,
Sorry for the late replay, I just saw your issue.
I'll try to reproduce & debug that.

**Comment by macmorning** [comment]
Corrected with version 2.4.0, the extension should be published soon.
