### ISSUE TITLE
Request: Add a "blocked sites" functionality

### ISSUE THREAD

**Issue by hormnn** [macmorning/pomodoro-webext#21]
Hi macmorning,

I have been using this for a while now and I like how simple and straightforward the add-on is. 

However, I find myself too distracted sometimes and it would be great to add some form of "blocked sites" functionality where you can specify a list of websites which the add-on will "block" during the streak duration.

Thanks.

**Comment by macmorning** [comment]
Hello,
Thanks a lot for your feedback!
Sadly it would be very intrusive and require the widest privileges. I think there are other extensions that can do that for you though, on FF & Chrome.
