### ISSUE TITLE
Request for pausing the timer

### ISSUE THREAD

**Issue by Xxx-in** [macmorning/pomodoro-webext#24]
Sometimes when I'm done with my study loop for the day, I'd like to turn off the pomodoro timer. However, it seems like I could only disable the extension completely to stop the timer for now. I'm using the firefox btw.

**Comment by macmorning** [comment]
Hello,
Thank you for your feedback.
Is the extension up to date? You can already stop the clock by clicking the "reset" button or clicking the clock itself to pause it.
