### ISSUE TITLE
Request to add a 'Dark Theme'

### ISSUE THREAD

**Issue by GonzaloOliveraAlves** [macmorning/pomodoro-webext#25]
I'm really digging Pomodoro Clock but it would be cool to have a dark theme for it that can blend in well with the rest of my stuff.

**Comment by macmorning** [comment]
Hello,
I'd rather not add more options, but I'll try to see if and how we can use current browser colors.

**Comment by macmorning** [comment]
Delivered with version 2.5.0, which is up for Firefox, soon for Chrome and Edge. I hope it's working for you as expected!
