### ISSUE TITLE
What is "Timers"

### ISSUE THREAD

**Issue by JLuc** [macmorning/pomodoro-webext#27]
Top window text is "Timers:" and there is an input zone displaying "30,5".
But it's not clear what its use and how to set it.
- The little "(?)" right next to "Timers:" does nothing
- Setting a new value (eg 100 instead of 30,5, and press enter) does nothing. 
And when later reopening the window, 30,5 is again displayed.

Running Firefox 105.0.2 on Ubuntu 22.04

[EDIT] Oh i see. "Timers:" input requires "Reset" button use.

**Comment by macmorning** [comment]
The helptext should be displayed when you hover on the "?" icon but it's not quite explicit and should be corrected.
Indeed, you need to reset or start the clock, else it's not saved.
You can describe a full streak/break sequence that will be repeating, for example 30,5,30,5,30,15 will let you have a larger third break.
![image](https://user-images.githubusercontent.com/1563892/194908361-e1638a49-83d9-41fa-b5bf-dd219e7a5d25.png)

**Comment by JLuc** [comment]
Ok i see.
Thanks for the explanations !

1) with carefull attention, i see the help hint pops up a fraction of second and disappear immediatly :-/

2) even with such a short hint, i dont think i would have understood. 
The help hint should say that the comma separated value list should list a sequence of streak and break lengths that will later be timed + it should explain that after input, user must press the "Start" or "Reset" button for the input to be of any use

**3) once the input has been edited, pressing Enter should launch or stop the timer !**

**Comment by macmorning** [comment]
Thank you JLuc,
I've added a more extensive hint in the options panel with v2.4.1, let me know if you feel it's clearer that way once the extension is updated for your browser. Does the hint stay open on the options page for you?
Regarding the start/reset, I'm not so sure because it's the normal use for the extension, with or without custom timers.
