### ISSUE TITLE
It's not working anymore

### ISSUE THREAD

**Issue by jamoness** [macmorning/pomodoro-webext#29]
After it starts and the initial time is up, it does not continue with the timeout, it just stops and does not even make the sound notification.

I don't know what has happened or if it is a setting in my browser.

Edit: I had deactivated it for several months, I don't know if that has affected its use.

**Comment by macmorning** [comment]
Hey,
What browser / version are you using?
You can try uninstalling the extension and reinstalling it.
Then please post a screenshot of your settings.

**Comment by jamoness** [comment]
Hi! 
I tried uninstalling it and didn't work; now it only show the notification when the initial time is up, it doesn't continue with the break and so on.
I'm using Firefox 112.0.2 (64-bit) and Pomodoro clock 2.4.1.

![Pomodoro settings](https://user-images.githubusercontent.com/35075812/234742401-18a359c1-cfa3-493b-96dc-4c1389b44c1f.png)

**Comment by macmorning** [comment]
You are using advanced timers, what have you set them to ?
You should have an even number of minutes with ; as a separator, like
"30;5;30;5;30;10".

**Comment by jamoness** [comment]
I have tried both the basic and advanced settings and the problem remains. In the advanced one I tried with "30;5;30;5;30;10" as you said but it doesn't work, when I start the time it erases the numbers after ";" so I tried with the "30,5,30,5,30,10" but it stops after the initial time is up.

While in the basic one, no matter what time I configure it never continues, it stops when the initial time is over.

**Comment by macmorning** [comment]
Hello, back from holidays, I just see you have "Do not loop automatically" checked. I didn't even remember this option existed and wonder why it does. :)
Uncheck it and save, it should solve your issue.

**Comment by macmorning** [comment]
Closing now, let me know if it didn't solve the issue.

**Comment by jamoness** [comment]
Ohhhhhh I'm a fool!!
I don't know why I didn't unchecked it during my adjustments to see what was going wrong or why I had it active. But thanks for the patience, now it's working a treat as always!! Best software (app or extension) I've tried for this purpose!
