### ISSUE TITLE
suspend media tab on change of cycle, rest to work or vice versa

### ISSUE THREAD

**Issue by Frankiesayscode** [macmorning/pomodoro-webext#32]
It would be nice to get the notification and suspend and re-enable media on the site authorised in the app. Is this possible?

Thanks for producing the excellent tool regardless.

**Comment by macmorning** [comment]
Hello sorry for the late reply, I would really prefer to keep this extension as simple as possible with minimal required permissions, and interfering with tabs/medias would require too much work and privileges.
