### ISSUE TITLE
Save streak duration

### ISSUE THREAD

**Issue by spacegramming** [macmorning/pomodoro-webext#4]
First of all thanks for your great work. 

It would be very useful if the streak and break duration could also be saved similar to the volume. I would to have 25min streaks, but as soon I close the window and open it again it is back to 30min.

**Comment by macmorning** [comment]
Hi,
Right now, the default streak and break timers are supposed to be saved in local storage when you click "start". Can you confirm that this is working?
If yes, do you mean that you'd like to set these values manually in the options instead?

**Comment by spacegramming** [comment]
> Right now, the default streak and break timers are supposed to be saved in local storage when you click "start". Can you confirm that this is working?
Yes, it works. When I tried it out previously it did not, so there must have been an issue with my firefox then. 
> If yes, do you mean that you'd like to set these values manually in the options instead?
Just as an idea: you could move the sliders to the options to make the main window a little bit smaller. I assume most people will not change their streak and break times too often.

**Comment by macmorning** [comment]
Yup, or we could just give the choice. In Firefox, the options page is not as quickly shown & dismissed as in Chrome.
I'll look into this, thanks for your feedback. :)

**Comment by macmorning** [comment]
Closing this issue because we can already configure the durations of streaks and pauses directly in the browser action popup. Moving them to the options pages would save some space in the popup, but we don't really need space for anything I can think of.
If you see that the durations are not saved automatically, please create an issue.
