### ISSUE TITLE
Customize timer sound

### ISSUE THREAD

**Issue by umlautfever** [macmorning/pomodoro-webext#6]
add option to add a custom notification sound (possibly "add url")

**Comment by macmorning** [comment]
Thanks for your suggestion.
I'll try to find a way to add this without requiring another permission.

**Comment by macmorning** [comment]
Delivered with version 2.0.0. Let me know if the way it is implemented suits your need.

**Comment by umlautfever** [comment]
works like a charm, thanks!!
