### ISSUE TITLE
Size / color options on the time remaining indicator

### ISSUE THREAD

**Issue by sksimmons** [macmorning/pomodoro-webext#8]
It'd be great if there was an option to change the size/coloring of the time remaining indicator.  It's pretty small, and when it's white text on a red background it's almost impossible for me to read.

**Comment by macmorning** [comment]
The size of the "badges" used to display informations on the icon is not settable by the extension.
We can use different background colors though. Do you think it's a contrast issue or is it specific to the ones I use currently? 
Thanks for your input!

**Comment by sksimmons** [comment]
I'm not sure.  The hi-cyan background when it's paused is better, and the dark grey background when the break timer is running is good.  Would it be possible to add a color palette for users to pick from?  I think different users may have trouble with different color combinations, so it'd be better if each user could pick what works for them.  Cool extension though!

**Comment by macmorning** [comment]
I don't have enough time to add a palette customization for now (but anyone is welcome to send a pull request), but as a workaround I changed the background color for the badge. Hopefully you will find it more readable that way.
